version: "3"

services:
  daytona-docker-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
    hostname: daytona-docker-extension
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    cap_add:
      - SYS_TTY_CONFIG
