name: ci

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version to release"
        required: true
        default: '0.42.1'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: daytonaio/daytona-docker-extension:${{ github.event.inputs.version }}
          build-args: |
            "DAYTONA_VERSION=v${{ github.event.inputs.version }}"
